FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install --frozen-lockfile

RUN pnpm exec prisma generate

COPY . .

ENV PORT=3000

EXPOSE ${PORT}

CMD ["pnpm", "start:dev"]