name: Lint
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"
      - name: Install dependencies
        run: pnpm install

      - name: Eslint
        run: pnpm run lint