name: Tests and Coverage
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Testing whith coverage
        run: pnpm run test:e2e
